export const MAX_PLAYGROUND_SELECTION: number;
type Profile = { productId: string; kind: string; name: string; brand: string; scene: string };
export type PlaygroundScene = 'ground' | 'aerial';
export type PlaygroundSelection = { scene: PlaygroundScene; picks: Record<PlaygroundScene, string[]> };
export type PlaygroundPreferences = { volume: number; quality: string };
export function profileScene(profile: Profile): PlaygroundScene | null;
export function profileGroup(profile: Profile): string;
export function togglePlaygroundSelection(ids: string[], id: string): { ids: string[]; limited: boolean };
export function filterPlaygroundProfiles<T extends Profile>(profiles: T[], group?: string, search?: string): T[];
export function sceneProfiles<T extends Profile>(profiles: T[], ids: string[], scene: string): T[];
export function restorePlaygroundSelection(profiles: Profile[], value?: unknown): PlaygroundSelection;
export function updatePlaygroundSelection(profiles: Profile[], value: PlaygroundSelection, action: { type: string; id?: string; scene?: string }): { state: PlaygroundSelection; limited: boolean; message: string };
export function getPlaygroundSession(profiles: Profile[], productId?: string): { state: PlaygroundSelection; limited: boolean; message: string };
export function savePlaygroundSession(profiles: Profile[], value: PlaygroundSelection): void;
export function sceneChangeMessage(scene: PlaygroundScene): string;
export function getPlaygroundPreferences(): PlaygroundPreferences;
export function savePlaygroundPreferences(value: unknown): void;
